// Generated by scripts/build-atlases.ts. Do not edit.

import type { AtlasManifest } from '../core/types/Atlas';
import smileysManifest from '../assets/atlases/smileys.json';
import smileysUrl from '../assets/atlases/smileys.webp';
import peopleManifest from '../assets/atlases/people.json';
import peopleUrl from '../assets/atlases/people.webp';
import animalsManifest from '../assets/atlases/animals.json';
import animalsUrl from '../assets/atlases/animals.webp';
import foodManifest from '../assets/atlases/food.json';
import foodUrl from '../assets/atlases/food.webp';
import travelManifest from '../assets/atlases/travel.json';
import travelUrl from '../assets/atlases/travel.webp';
import activitiesManifest from '../assets/atlases/activities.json';
import activitiesUrl from '../assets/atlases/activities.webp';
import objectsManifest from '../assets/atlases/objects.json';
import objectsUrl from '../assets/atlases/objects.webp';
import symbolsManifest from '../assets/atlases/symbols.json';
import symbolsUrl from '../assets/atlases/symbols.webp';
import flagsManifest from '../assets/atlases/flags.json';
import flagsUrl from '../assets/atlases/flags.webp';
import tone1Manifest from '../assets/atlases/tone1.json';
import tone1Url from '../assets/atlases/tone1.webp';
import tone2Manifest from '../assets/atlases/tone2.json';
import tone2Url from '../assets/atlases/tone2.webp';
import tone3Manifest from '../assets/atlases/tone3.json';
import tone3Url from '../assets/atlases/tone3.webp';
import tone4Manifest from '../assets/atlases/tone4.json';
import tone4Url from '../assets/atlases/tone4.webp';
import tone5Manifest from '../assets/atlases/tone5.json';
import tone5Url from '../assets/atlases/tone5.webp';

/** Every bundled atlas. The image is only a URL: the browser fetches it when one of its sprites is first shown. */
export const BUNDLED_ATLASES: ReadonlyArray<{ manifest: AtlasManifest; url: string }> = [
  { manifest: smileysManifest as unknown as AtlasManifest, url: smileysUrl },
  { manifest: peopleManifest as unknown as AtlasManifest, url: peopleUrl },
  { manifest: animalsManifest as unknown as AtlasManifest, url: animalsUrl },
  { manifest: foodManifest as unknown as AtlasManifest, url: foodUrl },
  { manifest: travelManifest as unknown as AtlasManifest, url: travelUrl },
  { manifest: activitiesManifest as unknown as AtlasManifest, url: activitiesUrl },
  { manifest: objectsManifest as unknown as AtlasManifest, url: objectsUrl },
  { manifest: symbolsManifest as unknown as AtlasManifest, url: symbolsUrl },
  { manifest: flagsManifest as unknown as AtlasManifest, url: flagsUrl },
  { manifest: tone1Manifest as unknown as AtlasManifest, url: tone1Url },
  { manifest: tone2Manifest as unknown as AtlasManifest, url: tone2Url },
  { manifest: tone3Manifest as unknown as AtlasManifest, url: tone3Url },
  { manifest: tone4Manifest as unknown as AtlasManifest, url: tone4Url },
  { manifest: tone5Manifest as unknown as AtlasManifest, url: tone5Url },
];
